export { Container } from './container';
export { Header } from './header';
export { About } from './about';
export { Guide } from './guide';
export { Discount } from './discount';
export { Vegetables } from './vegetables';
export { Reviews } from './reviews';
export { Feedback } from './feedback';
export { Footer } from './footer';
